const menu :MenuItem[]= [
	{
		name:'vue2base',
		title:"vue2基本储备",
		icon:' ri-spy-line'
	},
	{
		name:'vue2base2',
		title:"vue2的TS储备",
		icon:'ri-sd-card-line'
	},
	{
		name:'vue2base3',
		title:"vue2全家桶",
		icon:'ri-u-disk-fill'
	},
	{
		name:'vue2base4',
		title:"vue2全家桶",
		icon:'ri-u-disk-fill'
	},
	{
		name:'vue2base5',
		title:"vue2基本原理",
		icon:'ri-terminal-window-fill'
	},
	{
		name:'vue2base6',
		title:"vue2源码分析（1）",
		icon:'ri-git-repository-line'
	},
	{
		name:'vue2base2',
		title:"vue2源码分析（2）",
		icon:'ri-git-repository-line'
	},
	{
		name:'vue2base2',
		title:"vue2源码分析（3）",
		icon:'ri-git-repository-line'
	},
	{
		name:'vue2base2',
		title:"vue2的SSR",
		icon:'ri-tv-2-line'
	},
	{
		name:'vue2base2',
		title:"Vue2项目最佳实践",
		icon:'ri-cpu-fill'
	},
]

export default menu